var Hpf = require("hpf");
var Lpf = require("lpf");
var Hsf = require("hishelf");
var Lsf = require("loshelf");
var Peq = require("peq");
var rms = require("rms");

var hpf;
var lpf;
var hs;
var ls;
var lf;
var lmf;
var mf;
var hmf;
var hf;
var rmsPre;
var rmsPost;
function onInit(){
  addInput(["in","l"]);
  addInput(["in","r"]);
  addOutput(["out","l"]);
  addOutput(["out","r"]);
  //Bypass
  addParameter(["bypass"]);
  setParameterType(["bypass"], 1);
  setParameterStates(["bypass"], [0, 1], ["Unbypassed", "Bypassed"]);
  setParameterValue(["bypass"], 0, false);
  //Meter
  addParameter(["rms", "pre", "l"]);
  setParameterType(["rms", "pre", "l"], 0);
  setParameterRange(["rms", "pre", "l"], -inf, 10, 0.1, "dB");
  setParameterReadOnly(["rms", "pre", "l"], true);
  setParameterValue(["rms", "pre", "l"], -inf);
  addParameter(["rms", "pre", "r"]);
  setParameterType(["rms", "pre", "r"], 0);
  setParameterRange(["rms", "pre", "r"], -inf, 10, 0.1, "dB");
  setParameterReadOnly(["rms", "pre", "r"], true);
  setParameterValue(["rms", "pre", "r"], -inf);
  addParameter(["rms", "post", "l"]);
  setParameterType(["rms", "post", "l"], 0);
  setParameterRange(["rms", "post", "l"], -inf, 10, 0.1, "dB");
  setParameterReadOnly(["rms", "post", "l"], true);
  setParameterValue(["rms", "post", "l"], -inf);
  addParameter(["rms", "post", "r"]);
  setParameterType(["rms", "post", "r"], 0);
  setParameterRange(["rms", "post", "r"], -inf, 10, 0.1, "dB");
  setParameterReadOnly(["rms", "post", "r"], true);
  setParameterValue(["rms", "post", "r"], -inf);
  //HPF
  addParameter(["hpf", "bypass"]);
  setParameterType(["hpf", "bypass"], 1);
  setParameterStates(["hpf", "bypass"], [0, 1], ["Unbypassed", "Bypassed"]);
  setParameterValue(["hpf", "bypass"], 0, false);
  addParameter(["hpf", "freq"]);
  setParameterType(["hpf", "freq"], 0);
  setParameterRange(["hpf", "freq"], 20, 20000, 1, "Hz");
  setParameterValue(["hpf", "freq"], 20000, false);
  setParameterCallback(["hpf", "freq"], setCoeff);
  //LPF
  addParameter(["lpf", "bypass"]);
  setParameterType(["lpf", "bypass"], 1);
  setParameterStates(["lpf", "bypass"], [0, 1], ["Unbypassed", "Bypassed"]);
  setParameterValue(["lpf", "bypass"], 0, false);
  addParameter(["lpf", "freq"]);
  setParameterType(["lpf", "freq"], 0);
  setParameterRange(["lpf", "freq"], 20, 20000, 1, "Hz");
  setParameterValue(["lpf", "freq"], 20, false);
  setParameterCallback(["lpf", "freq"], setCoeff);
  //HS
  addParameter(["hs", "bypass"]);
  setParameterType(["hs", "bypass"], 1);
  setParameterStates(["hs", "bypass"], [0, 1], ["Unbypassed", "Bypassed"]);
  setParameterValue(["hs", "bypass"], 0, false);
  addParameter(["hs", "freq"]);
  setParameterType(["hs", "freq"], 0);
  setParameterRange(["hs", "freq"], 20, 20000, 1, "Hz");
  setParameterValue(["hs", "freq"], 20, false);
  setParameterCallback(["hs", "freq"], setCoeff);
  addParameter(["hs", "gain"]);
  setParameterType(["hs", "gain"], 0);
  setParameterRange(["hs", "gain"], -inf, 10, 0.1, "dB");
  setParameterValue(["hs", "gain"], 0, false);
  setParameterCallback(["hs", "gain"], setCoeff);
  //LS
  addParameter(["ls", "bypass"]);
  setParameterType(["ls", "bypass"], 1);
  setParameterStates(["ls", "bypass"], [0, 1], ["Unbypassed", "Bypassed"]);
  setParameterValue(["ls", "bypass"], 0, false);
  addParameter(["ls", "freq"]);
  setParameterType(["ls", "freq"], 0);
  setParameterRange(["ls", "freq"], 20, 20000, 1, "Hz");
  setParameterValue(["ls", "freq"], 20, false);
  setParameterCallback(["ls", "freq"], setCoeff);
  addParameter(["ls", "gain"]);
  setParameterType(["ls", "gain"], 0);
  setParameterRange(["ls", "gain"], -inf, 10, 0.1, "dB");
  setParameterValue(["ls", "gain"], 0, false);
  setParameterCallback(["ls", "gain"], setCoeff);
  //LF
  addParameter(["lf", "bypass"]);
  setParameterType(["lf", "bypass"], 1);
  setParameterStates(["lf", "bypass"], [0, 1], ["Unbypassed", "Bypassed"]);
  setParameterValue(["lf", "bypass"], 0, false);
  addParameter(["lf", "freq"]);
  setParameterType(["lf", "freq"], 0);
  setParameterRange(["lf", "freq"], 20, 20000, 1, "Hz");
  setParameterValue(["lf", "freq"], 20, false);
  setParameterCallback(["lf", "freq"], setCoeff);
  addParameter(["lf", "gain"]);
  setParameterType(["lf", "gain"], 0);
  setParameterRange(["lf", "gain"], -inf, 10, 0.1, "dB");
  setParameterValue(["lf", "gain"], 0, false);
  setParameterCallback(["lf", "gain"], setCoeff);
  addParameter(["lf", "q"]);
  setParameterType(["lf", "q"], 0);
  setParameterRange(["lf", "q"], 0, 1, 0.1, "");
  setParameterValue(["lf", "q"], 0.5, false);
  setParameterCallback(["lf", "q"], setCoeff);
  //LMF
  addParameter(["lmf", "bypass"]);
  setParameterType(["lmf", "bypass"], 1);
  setParameterStates(["lmf", "bypass"], [0, 1], ["Unbypassed", "Bypassed"]);
  setParameterValue(["lmf", "bypass"], 0, false);
  addParameter(["lmf", "freq"]);
  setParameterType(["lmf", "freq"], 0);
  setParameterRange(["lmf", "freq"], 20, 20000, 1, "Hz");
  setParameterValue(["lmf", "freq"], 20, false);
  setParameterCallback(["lmf", "freq"], setCoeff);
  addParameter(["lmf", "gain"]);
  setParameterType(["lmf", "gain"], 0);
  setParameterRange(["lmf", "gain"], -inf, 10, 0.1, "dB");
  setParameterValue(["lmf", "gain"], 0, false);
  setParameterCallback(["lmf", "gain"], setCoeff);
  addParameter(["lmf", "q"]);
  setParameterType(["lmf", "q"], 0);
  setParameterRange(["lmf", "q"], 0, 1, 0.1, "");
  setParameterValue(["lmf", "q"], 0.5, false);
  setParameterCallback(["lmf", "q"], setCoeff);
  //MF
  addParameter(["mf", "bypass"]);
  setParameterType(["mf", "bypass"], 1);
  setParameterStates(["mf", "bypass"], [0, 1], ["Unbypassed", "Bypassed"]);
  setParameterValue(["mf", "bypass"], 0, false);
  addParameter(["mf", "freq"]);
  setParameterType(["mf", "freq"], 0);
  setParameterRange(["mf", "freq"], 20, 20000, 1, "Hz");
  setParameterValue(["mf", "freq"], 20, false);
  setParameterCallback(["mf", "freq"], setCoeff);
  addParameter(["mf", "gain"]);
  setParameterType(["mf", "gain"], 0);
  setParameterRange(["mf", "gain"], -inf, 10, 0.1, "dB");
  setParameterValue(["mf", "gain"], 0, false);
  setParameterCallback(["mf", "gain"], setCoeff);
  addParameter(["mf", "q"]);
  setParameterType(["mf", "q"], 0);
  setParameterRange(["mf", "q"], 0, 1, 0.1, "");
  setParameterValue(["mf", "q"], 0.5, false);
  setParameterCallback(["mf", "q"], setCoeff);
  //HMF
  addParameter(["hmf", "bypass"]);
  setParameterType(["hmf", "bypass"], 1);
  setParameterStates(["hmf", "bypass"], [0, 1], ["Unbypassed", "Bypassed"]);
  setParameterValue(["hmf", "bypass"], 0, false);
  addParameter(["hmf", "freq"]);
  setParameterType(["hmf", "freq"], 0);
  setParameterRange(["hmf", "freq"], 20, 20000, 1, "Hz");
  setParameterValue(["hmf", "freq"], 20, false);
  setParameterCallback(["hmf", "freq"], setCoeff);
  addParameter(["hmf", "gain"]);
  setParameterType(["hmf", "gain"], 0);
  setParameterRange(["hmf", "gain"], -inf, 10, 0.1, "dB");
  setParameterValue(["hmf", "gain"], 0, false);
  setParameterCallback(["hmf", "gain"], setCoeff);
  addParameter(["hmf", "q"]);
  setParameterType(["hmf", "q"], 0);
  setParameterRange(["hmf", "q"], 0, 1, 0.1, "");
  setParameterValue(["hmf", "q"], 0.5, false);
  setParameterCallback(["hmf", "q"], setCoeff);
  //HF
  addParameter(["hf", "bypass"]);
  setParameterType(["hf", "bypass"], 1);
  setParameterStates(["hf", "bypass"], [0, 1], ["Unbypassed", "Bypassed"]);
  setParameterValue(["hf", "bypass"], 0, false);
  addParameter(["hf", "freq"]);
  setParameterType(["hf", "freq"], 0);
  setParameterRange(["hf", "freq"], 20, 20000, 1, "Hz");
  setParameterValue(["hf", "freq"], 20, false);
  setParameterCallback(["hf", "freq"], setCoeff);
  addParameter(["hf", "gain"]);
  setParameterType(["hf", "gain"], 0);
  setParameterRange(["hf", "gain"], -inf, 10, 0.1, "dB");
  setParameterValue(["hf", "gain"], 0, false);
  setParameterCallback(["hf", "gain"], setCoeff);
  addParameter(["hf", "q"]);
  setParameterType(["hf", "q"], 0);
  setParameterRange(["hf", "q"], 0, 1, 0.1, "");
  setParameterValue(["hf", "q"], 0.5, false);
  setParameterCallback(["hf", "q"], setCoeff);
  
  hpf[0] = new Hpf();
  hpf[1] = new Hpf();
  lpf[0] = new Lpf();
  lpf[1] = new Lpf();
  hs[0] = new Hsf();
  hs[1] = new Hsf();
  ls[0] = new Lsf();
  ls[1] = new Lsf();
  lf[0] = new Peq();
  lf[1] = new Peq();
  lmf[0] = new Peq();
  lmf[1] = new Peq();
  mf[0] = new Peq();
  mf[1] = new Peq();
  hmf[0] = new Peq();
  hmf[1] = new Peq();
  hf[0] = new Peq();
  hf[1] = new Peq();
  rmsPre[0] = new rms();
  rmsPre[1] = new rms();
  rmsPost[0] = new rms();
  rmsPost[1] = new rms();
}
